name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd iAPSAdvisor
          swift build
      - name: Test
        run: |
          cd iAPSAdvisor
          swift test
